# Generated by Django 4.1.4 on 2024-07-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noss', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
