# Generated by Django 5.0.7 on 2024-08-05 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='directories', to=settings.AUTH_USER_MODEL),
        ),
    ]
