# Generated by Django 5.0.7 on 2024-08-05 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_directory_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='members',
        ),
        migrations.AddField(
            model_name='directory',
            name='edit_permissions',
            field=models.ManyToManyField(blank=True, related_name='editable_directories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directory',
            name='view_permissions',
            field=models.ManyToManyField(blank=True, related_name='viewable_directories', to=settings.AUTH_USER_MODEL),
        ),
    ]
