# Generated by Django 5.0.7 on 2024-07-28 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
