# Generated by Django 5.0.7 on 2024-08-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_verification_code'),
        ('users', '0004_alter_user_verification_code_project'),
    ]

    operations = [
    ]
