# Generated by Django 5.0.7 on 2024-08-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_project_description_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_directories', to='users.project')),
            ],
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('name', models.CharField(max_length=255)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.codedirectory')),
            ],
        ),
    ]
