# Generated by Django 4.1.4 on 2024-07-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('developer', 'Developer')], max_length=10, null=True),
        ),
    ]
