# Generated by Django 4.1.4 on 2024-08-02 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_directory_alter_codefile_directory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project', 'permission_type')},
            },
        ),
        migrations.RemoveField(
            model_name='directory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='directory',
            name='project',
        ),
        migrations.DeleteModel(
            name='CodeFile',
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
    ]
