pipeline {
    agent any

    environment {
        SQLITE_DB_PATH = 'crud/db.sqlite3'
    }

     stages {
        stage('Checkout') {
            steps {
                // Checkout the code from your repository
                git 'https://github.com/BS-PMC-2024/BS-PMC-2024-Team30.git'
            }
        }

    }
}