pipeline {
    agent none

    stages{
        stage('Build') {
            agent{
                docker{
                    image 'python:3:10'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
    

        stage('Run Tests') {
            agent{
                docker{
                    image 'qnib/pytest'
                }
            }
            steps {                    
                sh 'python manage.py test noss/tests'
            }
            post{
                always {
                    junit 'test-report/results.xml'
                }
            }
        }
    }
}
